"""schema initial (create_all + _MIGRATIONS historique)

Revision ID: ae4fc0457052
Revises: 
Create Date: 2026-08-24 21:25:14.938011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae4fc0457052'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coproprietes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('ville', sa.String(), nullable=True),
    sa.Column('code_postal', sa.String(), nullable=True),
    sa.Column('annee_construction', sa.Integer(), nullable=True),
    sa.Column('regles_pays', sa.String(), nullable=True),
    sa.Column('devise', sa.String(), nullable=True),
    sa.Column('fonds_travaux_actif', sa.Boolean(), nullable=True),
    sa.Column('fonds_travaux_taux_pct', sa.Float(), nullable=True),
    sa.Column('fonds_travaux_compte', sa.String(), nullable=True),
    sa.Column('compte_bancaire_separe', sa.String(), nullable=True),
    sa.Column('smtp_host', sa.String(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(), nullable=True),
    sa.Column('smtp_password', sa.String(), nullable=True),
    sa.Column('email_expediteur', sa.String(), nullable=True),
    sa.Column('frontend_url', sa.String(), nullable=True),
    sa.Column('relance_auto', sa.Boolean(), nullable=True),
    sa.Column('relance_frequence', sa.String(), nullable=True),
    sa.Column('relance_jour', sa.Integer(), nullable=True),
    sa.Column('relance_heure', sa.String(), nullable=True),
    sa.Column('relance_minimum', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copropriete_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('heure', sa.String(), nullable=True),
    sa.Column('type_ag', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('lieu', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rappel_jours', sa.Integer(), nullable=True),
    sa.Column('convocation_envoyee', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['copropriete_id'], ['coproprietes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copropriete_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('categorie', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('site_web', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['copropriete_id'], ['coproprietes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copropriete_id', sa.Integer(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=True),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('fichier', sa.String(), nullable=True),
    sa.Column('date_ajout', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['copropriete_id'], ['coproprietes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copropriete_id', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('cloture', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['copropriete_id'], ['coproprietes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exercices_annee', 'exercices', ['annee'], unique=False)

    op.create_table('personnes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copropriete_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('est_proprietaire', sa.Boolean(), nullable=True),
    sa.Column('est_occupant', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['copropriete_id'], ['coproprietes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copropriete_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=True),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['copropriete_id'], ['coproprietes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=True),
    sa.Column('copropriete_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['copropriete_id'], ['coproprietes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)

    op.create_table('ag_creneaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ag_id', sa.Integer(), nullable=False),
    sa.Column('debut', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ag_id'], ['ags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appels_fonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercice_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('date_emission', sa.Date(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('montant_total', sa.Float(), nullable=True),
    sa.Column('inclut_fonds_travaux', sa.Boolean(), nullable=True),
    sa.Column('fonds_travaux_montant', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exercice_id'], ['exercices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercice_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('type_repartition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exercice_id'], ['exercices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copropriete_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.String(), nullable=True),
    sa.Column('date_fin', sa.String(), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('periode', sa.String(), nullable=True),
    sa.Column('renouvellement_auto', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['copropriete_id'], ['coproprietes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ag_id', sa.Integer(), nullable=False),
    sa.Column('personne_id', sa.Integer(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ag_id'], ['ags.id'], ),
    sa.ForeignKeyConstraint(['personne_id'], ['personnes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copropriete_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('tantiemes', sa.Integer(), nullable=True),
    sa.Column('surface_m2', sa.Float(), nullable=True),
    sa.Column('proprietaire_id', sa.Integer(), nullable=True),
    sa.Column('occupant_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['copropriete_id'], ['coproprietes.id'], ),
    sa.ForeignKeyConstraint(['occupant_id'], ['personnes.id'], ),
    sa.ForeignKeyConstraint(['proprietaire_id'], ['personnes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ag_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=True),
    sa.Column('majorite', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ag_id'], ['ags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_coproprietes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('copropriete_id', sa.Integer(), nullable=False),
    sa.Column('principale', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['copropriete_id'], ['coproprietes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ag_creneau_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creneau_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('dispo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creneau_id'], ['ag_creneaux.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appels_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appel_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('montant_charges', sa.Float(), nullable=True),
    sa.Column('montant_fonds_travaux', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['appel_id'], ['appels_fonds.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carnet_entretien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copropriete_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type_intervention', sa.String(), nullable=True),
    sa.Column('prestataire', sa.String(), nullable=True),
    sa.Column('cout', sa.Float(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['copropriete_id'], ['coproprietes.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouvements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copropriete_id', sa.Integer(), nullable=False),
    sa.Column('exercice_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=True),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('appel_id', sa.Integer(), nullable=True),
    sa.Column('piece_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appel_id'], ['appels_fonds.id'], ),
    sa.ForeignKeyConstraint(['copropriete_id'], ['coproprietes.id'], ),
    sa.ForeignKeyConstraint(['exercice_id'], ['exercices.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('personne_id', sa.Integer(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('montant_du', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['personne_id'], ['personnes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('voix', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('relances')
    op.drop_table('mouvements')
    op.drop_table('carnet_entretien')
    op.drop_table('appels_lots')
    op.drop_table('ag_creneau_votes')
    op.drop_table('user_coproprietes')
    op.drop_table('resolutions')
    op.drop_table('lots')
    op.drop_table('invitations')
    op.drop_table('contrats')
    op.drop_table('budget_lines')
    op.drop_table('appels_fonds')
    op.drop_table('ag_creneaux')
    op.drop_table('users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('travaux')
    op.drop_table('personnes')
    op.drop_table('exercices')
    op.drop_index('ix_exercices_annee', table_name='exercices')
    op.drop_table('documents')
    op.drop_table('contacts')
    op.drop_table('ags')
    op.drop_table('coproprietes')
    # ### end Alembic commands ###
